"""ORM models for VulnaDash.

Importing this package registers every model on ``Base.metadata`` so that
Alembic and ``metadata.create_all`` see the full schema.
"""

from app.models.asset import Asset, AssetIdentifier
from app.models.asset_context import (
    AssetGroup,
    AssetGroupMembership,
    AssetOwnershipHistory,
    AssetTag,
    AssetTagAssignment,
    DepartmentOwner,
)
from app.models.audit import AuditEvent
from app.models.authorization import (
    ApiToken,
    AuthorizationRole,
    RolePermission,
    ScopedGrant,
    ServiceAccount,
)
from app.models.background_task import BackgroundTask, WorkerHeartbeat
from app.models.change_event import ChangeEvent
from app.models.credential import (
    CredentialAssignment,
    CredentialRecord,
    CredentialSecretVersion,
    CredentialTest,
    CredentialUsageAudit,
)
from app.models.cve import CveRecord, ThreatIntelEnrichment
from app.models.enrollment_token import EnrollmentToken
from app.models.enums import (
    AccountStatus,
    ActorType,
    AssetCriticality,
    AssetEnvironment,
    AssetGroupType,
    AssetMembershipSource,
    AssetStatus,
    AssetTagSource,
    AssetType,
    AuthenticationSource,
    BackgroundTaskStatus,
    ChangeEventType,
    CredentialAssignmentTarget,
    CredentialAuthType,
    CredentialProtocol,
    CredentialTestStatus,
    CredentialUsageStatus,
    DataClassification,
    EolStatus,
    FeedSource,
    FeedStatus,
    FindingDecisionStatus,
    FindingDecisionType,
    FindingStatus,
    FindingType,
    GrantScopeType,
    IdentifierType,
    IdentityProviderProtocol,
    JobMode,
    JobStatus,
    MatchConfidence,
    OwnershipSource,
    PentestSessionStatus,
    PrincipalType,
    ProbeStatus,
    RelayStatus,
    RemediationKeyType,
    RemediationSuggestionStatus,
    RemediationUnitStatus,
    ReportFormat,
    ReportStatus,
    ReportType,
    RiskAcceptanceStatus,
    ServiceAccountStatus,
    ServiceState,
    ServiceTransport,
    Severity,
    SiteAccessMode,
    SoftwareChangeType,
    SoftwareInventorySource,
    SsoPolicyMode,
    UserRole,
    ValidationStatus,
    WebScanProfile,
    WorkflowRunStatus,
    WorkflowStageStatus,
)
from app.models.feed_health import FeedHealth
from app.models.finding import Finding
from app.models.finding_note import FindingNote
from app.models.mfa import (
    AuthenticationThrottle,
    MfaPolicy,
    MfaRecoveryCode,
    TotpFactor,
    WebAuthnChallenge,
    WebAuthnCredential,
)
from app.models.network import Network, NetworkScout
from app.models.network_scope import NetworkScope
from app.models.notification import NotificationChannel, NotificationDelivery
from app.models.onboarding import OnboardingState
from app.models.organization import Organization
from app.models.pentest_session import PentestSession
from app.models.probe import Probe
from app.models.probe_result_upload import ProbeResultUpload
from app.models.relay import Relay
from app.models.report import Report
from app.models.retention_hold import RetentionHold
from app.models.risk import (
    FindingDecision,
    FindingScoreSnapshot,
    RemediationSuggestion,
    RemediationUnit,
    RemediationUnitFinding,
    RiskProfile,
)
from app.models.risk_acceptance import RiskAcceptance
from app.models.rules_of_engagement import RulesOfEngagement
from app.models.scan_artifact import ScanArtifact
from app.models.scan_job import ScanJob
from app.models.scan_schedule import ScanSchedule
from app.models.scim import (
    ScimGroup,
    ScimGroupMember,
    ScimGroupSiteMapping,
    ScimProvisioningLog,
    ScimRateLimitWindow,
    ScimToken,
)
from app.models.service import Service
from app.models.session import SessionRefreshToken, UserSession
from app.models.site import Site
from app.models.software import (
    EolIntelligenceRecord,
    EolOverride,
    SoftwareInventoryHistory,
    SoftwareInventoryItem,
)
from app.models.sso import (
    ExternalIdentityLink,
    IdentityGroupMapping,
    IdentityProvider,
    IdentityProviderTest,
    SamlReplayRecord,
    SsoPolicy,
    SsoProtocolState,
)
from app.models.user import User
from app.models.user_lifecycle import (
    PasswordResetToken,
    UserInvitation,
    UserLifecycleEvent,
    UserSiteAssignment,
)
from app.models.workflow_run import WorkflowRun

__all__ = [
    "AccountStatus",
    "ActorType",
    "Asset",
    "AssetCriticality",
    "AssetEnvironment",
    "AssetGroup",
    "AssetGroupMembership",
    "AssetGroupType",
    "AssetIdentifier",
    "AssetMembershipSource",
    "AssetOwnershipHistory",
    "AssetStatus",
    "AssetTag",
    "AssetTagAssignment",
    "AssetTagSource",
    "AssetType",
    "AuthenticationSource",
    "BackgroundTask",
    "BackgroundTaskStatus",
    "AuthenticationThrottle",
    "ApiToken",
    "AuthorizationRole",
    "AuditEvent",
    "ChangeEvent",
    "ChangeEventType",
    "CredentialAssignment",
    "CredentialAssignmentTarget",
    "CredentialAuthType",
    "CredentialProtocol",
    "CredentialRecord",
    "CredentialSecretVersion",
    "CredentialTest",
    "CredentialTestStatus",
    "CredentialUsageAudit",
    "CredentialUsageStatus",
    "CveRecord",
    "DataClassification",
    "EolIntelligenceRecord",
    "EolOverride",
    "EolStatus",
    "DepartmentOwner",
    "EnrollmentToken",
    "ExternalIdentityLink",
    "FeedHealth",
    "FeedSource",
    "FeedStatus",
    "Finding",
    "FindingNote",
    "FindingStatus",
    "FindingDecision",
    "FindingDecisionStatus",
    "FindingDecisionType",
    "FindingScoreSnapshot",
    "FindingType",
    "GrantScopeType",
    "IdentifierType",
    "IdentityGroupMapping",
    "IdentityProvider",
    "IdentityProviderProtocol",
    "IdentityProviderTest",
    "JobMode",
    "JobStatus",
    "MatchConfidence",
    "MfaPolicy",
    "MfaRecoveryCode",
    "Network",
    "NetworkScout",
    "NetworkScope",
    "NotificationChannel",
    "NotificationDelivery",
    "OnboardingState",
    "Organization",
    "OwnershipSource",
    "PentestSession",
    "PentestSessionStatus",
    "PasswordResetToken",
    "Probe",
    "ProbeResultUpload",
    "ProbeStatus",
    "PrincipalType",
    "Relay",
    "RelayStatus",
    "Report",
    "RetentionHold",
    "ReportFormat",
    "ReportStatus",
    "ReportType",
    "RiskAcceptance",
    "RiskAcceptanceStatus",
    "RiskProfile",
    "RemediationKeyType",
    "RemediationSuggestion",
    "RemediationSuggestionStatus",
    "RemediationUnit",
    "RemediationUnitFinding",
    "RemediationUnitStatus",
    "RulesOfEngagement",
    "ScanArtifact",
    "ScanJob",
    "ScanSchedule",
    "SamlReplayRecord",
    "Service",
    "ServiceAccount",
    "ServiceAccountStatus",
    "ServiceState",
    "ServiceTransport",
    "SessionRefreshToken",
    "RolePermission",
    "ScopedGrant",
    "Severity",
    "Site",
    "SiteAccessMode",
    "SoftwareChangeType",
    "SoftwareInventoryHistory",
    "SoftwareInventoryItem",
    "SoftwareInventorySource",
    "SsoPolicy",
    "SsoPolicyMode",
    "SsoProtocolState",
    "ScimGroup",
    "ScimGroupMember",
    "ScimGroupSiteMapping",
    "ScimProvisioningLog",
    "ScimRateLimitWindow",
    "ScimToken",
    "ThreatIntelEnrichment",
    "TotpFactor",
    "User",
    "UserInvitation",
    "UserLifecycleEvent",
    "UserRole",
    "UserSiteAssignment",
    "UserSession",
    "ValidationStatus",
    "WebScanProfile",
    "WorkerHeartbeat",
    "WebAuthnChallenge",
    "WebAuthnCredential",
    "WorkflowRun",
    "WorkflowRunStatus",
    "WorkflowStageStatus",
]
