"""phase 5: change events

Revision ID: 05c28372c891
Revises: a8b9a84a342c
Create Date: 2026-07-10 08:48:04.790405
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '05c28372c891'
down_revision: str | None = 'a8b9a84a342c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_events',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('scan_job_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.Enum('ASSET_DISCOVERED', 'ASSET_DISAPPEARED', 'IP_CHANGED', 'NEW_PORT_OPENED', 'PORT_CLOSED', 'SERVICE_VERSION_CHANGED', name='changeeventtype', native_enum=False, length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.String(length=512), nullable=False),
    sa.Column('before_json', sa.JSON(), nullable=False),
    sa.Column('after_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_change_events_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_change_events_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_job_id'], ['scan_jobs.id'], name=op.f('fk_change_events_scan_job_id_scan_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_change_events_site_id_sites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_change_events'))
    )
    with op.batch_alter_table('change_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_change_events_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_events_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_events_scan_job_id'), ['scan_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_events_site_id'), ['site_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('change_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_change_events_site_id'))
        batch_op.drop_index(batch_op.f('ix_change_events_scan_job_id'))
        batch_op.drop_index(batch_op.f('ix_change_events_organization_id'))
        batch_op.drop_index(batch_op.f('ix_change_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_change_events_asset_id'))

    op.drop_table('change_events')
    # ### end Alembic commands ###
