"""phase 7: cve intelligence

Revision ID: 5506b3eb7483
Revises: ad1939b84d3a
Create Date: 2026-07-10 10:13:19.004432
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5506b3eb7483'
down_revision: str | None = 'ad1939b84d3a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cve_records',
    sa.Column('cve_id', sa.String(length=32), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cvss_v2_json', sa.JSON(), nullable=True),
    sa.Column('cvss_v3_json', sa.JSON(), nullable=True),
    sa.Column('cvss_v4_json', sa.JSON(), nullable=True),
    sa.Column('cwe_ids_json', sa.JSON(), nullable=False),
    sa.Column('cpe_matches_json', sa.JSON(), nullable=False),
    sa.Column('references_json', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('rejected', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('cve_id', name=op.f('pk_cve_records'))
    )
    op.create_table('feed_health',
    sa.Column('source', sa.Enum('NVD', 'KEV', 'EPSS', name='feedsource', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('OK', 'DEGRADED', 'FAILED', 'STALE', 'NEVER_SYNCED', name='feedstatus', native_enum=False, length=16), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('records_changed', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('last_source_timestamp', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('source', name=op.f('pk_feed_health'))
    )
    op.create_table('threat_intel_enrichments',
    sa.Column('cve_id', sa.String(length=32), nullable=False),
    sa.Column('is_kev', sa.Boolean(), nullable=False),
    sa.Column('kev_date_added', sa.Date(), nullable=True),
    sa.Column('kev_due_date', sa.Date(), nullable=True),
    sa.Column('kev_required_action', sa.Text(), nullable=True),
    sa.Column('known_ransomware_use', sa.Boolean(), nullable=False),
    sa.Column('epss_score', sa.Float(), nullable=True),
    sa.Column('epss_percentile', sa.Float(), nullable=True),
    sa.Column('epss_date', sa.Date(), nullable=True),
    sa.Column('previous_epss_score', sa.Float(), nullable=True),
    sa.Column('public_exploit_available', sa.Boolean(), nullable=False),
    sa.Column('exploit_reference_json', sa.JSON(), nullable=False),
    sa.Column('last_enriched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('cve_id', name=op.f('pk_threat_intel_enrichments'))
    )
    with op.batch_alter_table('threat_intel_enrichments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_threat_intel_enrichments_is_kev'), ['is_kev'], unique=False)

    with op.batch_alter_table('findings', schema=None) as batch_op:
        # server_default so the NOT NULL add succeeds on tables with existing rows.
        batch_op.add_column(
            sa.Column('known_exploited', sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.add_column(sa.Column('epss_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('epss_percentile', sa.Float(), nullable=True))
        batch_op.create_index(batch_op.f('ix_findings_known_exploited'), ['known_exploited'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_findings_known_exploited'))
        batch_op.drop_column('epss_percentile')
        batch_op.drop_column('epss_score')
        batch_op.drop_column('known_exploited')

    with op.batch_alter_table('threat_intel_enrichments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_threat_intel_enrichments_is_kev'))

    op.drop_table('threat_intel_enrichments')
    op.drop_table('feed_health')
    op.drop_table('cve_records')
    # ### end Alembic commands ###
