"""phase 2: probes and enrollment tokens

Revision ID: 5a655260d35d
Revises: ce35fd2a15f8
Create Date: 2026-07-10 01:42:47.699381
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5a655260d35d'
down_revision: str | None = 'ce35fd2a15f8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollment_tokens',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('short_code', sa.String(length=16), nullable=False),
    sa.Column('probe_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_by_probe_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_enrollment_tokens_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_enrollment_tokens_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_enrollment_tokens_site_id_sites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrollment_tokens'))
    )
    with op.batch_alter_table('enrollment_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrollment_tokens_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollment_tokens_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollment_tokens_token_hash'), ['token_hash'], unique=True)

    op.create_table('probes',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.Enum('PENDING_ENROLLMENT', 'ENROLLED', 'DISABLED', 'REVOKED', name='probestatus', native_enum=False, length=32), nullable=False),
    sa.Column('certificate_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('certificate_serial', sa.String(length=64), nullable=True),
    sa.Column('certificate_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agent_version', sa.String(length=64), nullable=True),
    sa.Column('operating_system', sa.String(length=128), nullable=True),
    sa.Column('architecture', sa.String(length=32), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('primary_ip', sa.String(length=64), nullable=True),
    sa.Column('capabilities_json', sa.JSON(), nullable=False),
    sa.Column('health_json', sa.JSON(), nullable=False),
    sa.Column('policy_hash', sa.String(length=64), nullable=True),
    sa.Column('upgrade_channel', sa.String(length=32), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_job_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_probes_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_probes_site_id_sites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_probes'))
    )
    with op.batch_alter_table('probes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_probes_certificate_fingerprint'), ['certificate_fingerprint'], unique=True)
        batch_op.create_index(batch_op.f('ix_probes_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_probes_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_probes_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('probes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_probes_status'))
        batch_op.drop_index(batch_op.f('ix_probes_site_id'))
        batch_op.drop_index(batch_op.f('ix_probes_organization_id'))
        batch_op.drop_index(batch_op.f('ix_probes_certificate_fingerprint'))

    op.drop_table('probes')
    with op.batch_alter_table('enrollment_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrollment_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_enrollment_tokens_site_id'))
        batch_op.drop_index(batch_op.f('ix_enrollment_tokens_organization_id'))

    op.drop_table('enrollment_tokens')
    # ### end Alembic commands ###
