"""phase 19 onboarding state and recovery codes

Revision ID: 5fa1afe0d8e3
Revises: f5a784867dfc
Create Date: 2026-07-10 16:01:07.916701
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5fa1afe0d8e3'
down_revision: str | None = 'f5a784867dfc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_states',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('current_step', sa.String(length=32), nullable=False),
    sa.Column('completed_steps_json', sa.JSON(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=True),
    sa.Column('scope_id', sa.Uuid(), nullable=True),
    sa.Column('first_job_id', sa.Uuid(), nullable=True),
    sa.Column('demo_used', sa.Boolean(), nullable=False),
    sa.Column('dismissed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_onboarding_states_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_onboarding_states'))
    )
    with op.batch_alter_table('onboarding_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_onboarding_states_organization_id'), ['organization_id'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        # server_default so the NOT NULL add succeeds on existing rows; existing
        # users simply have no recovery codes until they generate them.
        batch_op.add_column(
            sa.Column(
                'recovery_codes_json',
                sa.JSON(),
                nullable=False,
                server_default=sa.text("'[]'"),
            )
        )
        batch_op.add_column(sa.Column('recovery_codes_generated_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('recovery_codes_generated_at')
        batch_op.drop_column('recovery_codes_json')

    with op.batch_alter_table('onboarding_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_onboarding_states_organization_id'))

    op.drop_table('onboarding_states')
    # ### end Alembic commands ###
