"""phase 8: reports

Revision ID: 7f2d80ee106f
Revises: 5506b3eb7483
Create Date: 2026-07-10 10:37:01.810262
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7f2d80ee106f'
down_revision: str | None = '5506b3eb7483'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=True),
    sa.Column('scan_job_id', sa.Uuid(), nullable=True),
    sa.Column('report_type', sa.Enum('EXECUTIVE_PDF', 'TECHNICAL_PDF', 'FINDINGS_CSV', 'ASSETS_CSV', 'SERVICES_CSV', 'CVE_EXPOSURE_CSV', 'JSON_BUNDLE', name='reporttype', native_enum=False, length=32), nullable=False),
    sa.Column('format', sa.Enum('PDF', 'CSV', 'JSON', name='reportformat', native_enum=False, length=8), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'GENERATING', 'COMPLETED', 'FAILED', name='reportstatus', native_enum=False, length=16), nullable=False),
    sa.Column('template_version', sa.String(length=32), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('generated_by', sa.Uuid(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(length=1024), nullable=True),
    sa.Column('parameters_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], name=op.f('fk_reports_generated_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_reports_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_job_id'], ['scan_jobs.id'], name=op.f('fk_reports_scan_job_id_scan_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_reports_site_id_sites'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_scan_job_id'), ['scan_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_site_id'), ['site_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_site_id'))
        batch_op.drop_index(batch_op.f('ix_reports_scan_job_id'))
        batch_op.drop_index(batch_op.f('ix_reports_organization_id'))

    op.drop_table('reports')
    # ### end Alembic commands ###
