"""phase 4: scan artifacts

Revision ID: a8b9a84a342c
Revises: ac042d545f26
Create Date: 2026-07-10 08:24:46.868241
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a8b9a84a342c'
down_revision: str | None = 'ac042d545f26'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_artifacts',
    sa.Column('scan_job_id', sa.Uuid(), nullable=False),
    sa.Column('probe_id', sa.Uuid(), nullable=True),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('scanner_name', sa.String(length=64), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('raw_output', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['probe_id'], ['probes.id'], name=op.f('fk_scan_artifacts_probe_id_probes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_job_id'], ['scan_jobs.id'], name=op.f('fk_scan_artifacts_scan_job_id_scan_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_artifacts'))
    )
    with op.batch_alter_table('scan_artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_artifacts_scan_job_id'), ['scan_job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_artifacts_scan_job_id'))

    op.drop_table('scan_artifacts')
    # ### end Alembic commands ###
