"""phase 4: assets and services

Revision ID: ac042d545f26
Revises: d1e5a28397c7
Create Date: 2026-07-10 08:19:49.958730
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ac042d545f26'
down_revision: str | None = 'd1e5a28397c7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.Enum('WORKSTATION', 'SERVER', 'NETWORK_DEVICE', 'PRINTER', 'CAMERA', 'PHONE', 'STORAGE', 'HYPERVISOR', 'VIRTUAL_MACHINE', 'CLOUD_INSTANCE', 'IOT', 'EMBEDDED', 'WEB_APPLICATION', 'UNKNOWN', name='assettype', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='assetstatus', native_enum=False, length=16), nullable=False),
    sa.Column('operating_system', sa.String(length=255), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('identity_confidence', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_assessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tags_json', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_assets_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_assets_site_id_sites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets'))
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_site_id'), ['site_id'], unique=False)

    op.create_table('asset_identifiers',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('identifier_type', sa.Enum('IP_ADDRESS', 'MAC_ADDRESS', 'HOSTNAME', 'FQDN', 'SMB_NAME', 'SSH_HOST_KEY', 'TLS_CERT_FINGERPRINT', 'SNMP_ENGINE_ID', 'CLOUD_INSTANCE_ID', 'AGENT_ID', name='identifiertype', native_enum=False, length=32), nullable=False),
    sa.Column('identifier_value', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_identifiers_asset_id_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_identifiers')),
    sa.UniqueConstraint('asset_id', 'identifier_type', 'identifier_value', name='uq_asset_identifiers_asset_type_value')
    )
    with op.batch_alter_table('asset_identifiers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_identifiers_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_identifiers_identifier_value'), ['identifier_value'], unique=False)

    op.create_table('services',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('transport', sa.Enum('TCP', 'UDP', 'SCTP', name='servicetransport', native_enum=False, length=8), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('OPEN', 'CLOSED', 'FILTERED', 'OPEN_FILTERED', 'UNFILTERED', name='servicestate', native_enum=False, length=16), nullable=False),
    sa.Column('service_name', sa.String(length=128), nullable=True),
    sa.Column('product', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=128), nullable=True),
    sa.Column('cpe', sa.String(length=255), nullable=True),
    sa.Column('banner_hash', sa.String(length=64), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_services_asset_id_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services')),
    sa.UniqueConstraint('asset_id', 'transport', 'port', name='uq_services_asset_transport_port')
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_services_asset_id'), ['asset_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_asset_id'))

    op.drop_table('services')
    with op.batch_alter_table('asset_identifiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_identifiers_identifier_value'))
        batch_op.drop_index(batch_op.f('ix_asset_identifiers_asset_id'))

    op.drop_table('asset_identifiers')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_site_id'))
        batch_op.drop_index(batch_op.f('ix_assets_organization_id'))

    op.drop_table('assets')
    # ### end Alembic commands ###
