"""phase 6: findings

Revision ID: ad1939b84d3a
Revises: 05c28372c891
Create Date: 2026-07-10 09:36:21.101432
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ad1939b84d3a'
down_revision: str | None = '05c28372c891'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('findings',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('service_id', sa.Uuid(), nullable=True),
    sa.Column('scan_job_id', sa.Uuid(), nullable=True),
    sa.Column('scanner_name', sa.String(length=64), nullable=False),
    sa.Column('scanner_finding_id', sa.String(length=255), nullable=True),
    sa.Column('canonical_finding_key', sa.String(length=64), nullable=False),
    sa.Column('finding_type', sa.Enum('VULNERABILITY', 'MISCONFIGURATION', 'WEAK_PROTOCOL', 'EXPOSED_SERVICE', 'DEFAULT_CREDENTIAL', 'MISSING_PATCH', 'UNSUPPORTED_SOFTWARE', 'WEB_APPLICATION_ISSUE', 'CREDENTIALED_CONFIGURATION_ISSUE', 'VALIDATED_EXPLOITABILITY', 'INFORMATIONAL', name='findingtype', native_enum=False, length=48), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='severity', native_enum=False, length=16), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('cvss_vector', sa.String(length=128), nullable=True),
    sa.Column('cve_ids_json', sa.JSON(), nullable=False),
    sa.Column('cwe_ids_json', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('validation_status', sa.Enum('UNVALIDATED', 'LIKELY', 'CONFIRMED_NON_EXPLOIT', 'CONFIRMED_EXPLOITABLE', 'INCONCLUSIVE', 'NOT_APPLICABLE', name='validationstatus', native_enum=False, length=32), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('references_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'TRIAGE', 'VALIDATED', 'ASSIGNED', 'REMEDIATION_IN_PROGRESS', 'READY_FOR_VERIFICATION', 'RESOLVED', 'REOPENED', 'RISK_ACCEPTED', 'FALSE_POSITIVE', 'DUPLICATE', 'SUPPRESSED', name='findingstatus', native_enum=False, length=32), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reopened_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_findings_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_findings_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_job_id'], ['scan_jobs.id'], name=op.f('fk_findings_scan_job_id_scan_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_findings_service_id_services'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_findings_site_id_sites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_findings'))
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_findings_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_canonical_finding_key'), ['canonical_finding_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_scan_job_id'), ['scan_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_findings_status'))
        batch_op.drop_index(batch_op.f('ix_findings_site_id'))
        batch_op.drop_index(batch_op.f('ix_findings_severity'))
        batch_op.drop_index(batch_op.f('ix_findings_scan_job_id'))
        batch_op.drop_index(batch_op.f('ix_findings_organization_id'))
        batch_op.drop_index(batch_op.f('ix_findings_canonical_finding_key'))
        batch_op.drop_index(batch_op.f('ix_findings_asset_id'))

    op.drop_table('findings')
    # ### end Alembic commands ###
