"""phase 3: scan jobs

Revision ID: d1e5a28397c7
Revises: 5a655260d35d
Create Date: 2026-07-10 02:38:42.404607
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd1e5a28397c7'
down_revision: str | None = '5a655260d35d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_jobs',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('probe_id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.Enum('VULNERABILITY_ASSESSMENT', 'CONTROLLED_PENTEST', 'FULL_SPECTRUM', name='jobmode', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'OFFERED', 'ACCEPTED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'EXPIRED', 'REJECTED_BY_PROBE', name='jobstatus', native_enum=False, length=32), nullable=False),
    sa.Column('requested_targets_json', sa.JSON(), nullable=False),
    sa.Column('workflow_json', sa.JSON(), nullable=False),
    sa.Column('limits_json', sa.JSON(), nullable=False),
    sa.Column('policy_version', sa.Integer(), nullable=False),
    sa.Column('envelope_json', sa.JSON(), nullable=False),
    sa.Column('job_signature', sa.String(length=128), nullable=False),
    sa.Column('not_before', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('offered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.String(length=2048), nullable=True),
    sa.Column('summary_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_scan_jobs_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_scan_jobs_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['probe_id'], ['probes.id'], name=op.f('fk_scan_jobs_probe_id_probes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_scan_jobs_site_id_sites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_jobs'))
    )
    with op.batch_alter_table('scan_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_jobs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_jobs_probe_id'), ['probe_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_jobs_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_jobs_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_scan_jobs_site_id'))
        batch_op.drop_index(batch_op.f('ix_scan_jobs_probe_id'))
        batch_op.drop_index(batch_op.f('ix_scan_jobs_organization_id'))

    op.drop_table('scan_jobs')
    # ### end Alembic commands ###
