"""phase 10: remediation and verification

Revision ID: e1bac3e00289
Revises: 7f2d80ee106f
Create Date: 2026-07-10 11:58:18.880392
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e1bac3e00289'
down_revision: str | None = '7f2d80ee106f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finding_notes',
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('author_user_id', sa.Uuid(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], name=op.f('fk_finding_notes_author_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_finding_notes_finding_id_findings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finding_notes'))
    )
    with op.batch_alter_table('finding_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finding_notes_finding_id'), ['finding_id'], unique=False)

    op.create_table('risk_acceptances',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('compensating_controls', sa.Text(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'EXPIRED', 'REVOKED', 'REJECTED', name='riskacceptancestatus', native_enum=False, length=16), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_risk_acceptances_approved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_risk_acceptances_finding_id_findings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_risk_acceptances_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_risk_acceptances_requested_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_acceptances'))
    )
    with op.batch_alter_table('risk_acceptances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_acceptances_finding_id'), ['finding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_acceptances_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_acceptances_status'), ['status'], unique=False)

    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_user_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('due_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('risk_acceptance_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('false_positive_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_findings_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_findings_owner_user_id_users'), 'users', ['owner_user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('scan_jobs', schema=None) as batch_op:
        # server_default so the NOT NULL add succeeds on tables with existing rows.
        batch_op.add_column(
            sa.Column(
                'verifies_finding_ids_json', sa.JSON(), nullable=False, server_default='[]'
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_jobs', schema=None) as batch_op:
        batch_op.drop_column('verifies_finding_ids_json')

    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_findings_owner_user_id_users'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_findings_owner_user_id'))
        batch_op.drop_column('last_verified_at')
        batch_op.drop_column('false_positive_reason')
        batch_op.drop_column('risk_acceptance_id')
        batch_op.drop_column('due_at')
        batch_op.drop_column('owner_user_id')

    with op.batch_alter_table('risk_acceptances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_acceptances_status'))
        batch_op.drop_index(batch_op.f('ix_risk_acceptances_organization_id'))
        batch_op.drop_index(batch_op.f('ix_risk_acceptances_finding_id'))

    op.drop_table('risk_acceptances')
    with op.batch_alter_table('finding_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finding_notes_finding_id'))

    op.drop_table('finding_notes')
    # ### end Alembic commands ###
