"""phase 17: enrollment token auto_approve

Revision ID: f5a784867dfc
Revises: 834572a0ddd4
Create Date: 2026-07-10 14:15:37.039862
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f5a784867dfc'
down_revision: str | None = '834572a0ddd4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment_tokens', schema=None) as batch_op:
        # server_default so the NOT NULL add succeeds on tables with existing rows;
        # existing tokens are never auto-approve.
        batch_op.add_column(
            sa.Column('auto_approve', sa.Boolean(), nullable=False, server_default=sa.false())
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment_tokens', schema=None) as batch_op:
        batch_op.drop_column('auto_approve')

    # ### end Alembic commands ###
