"""Add authenticated, append-only audit chains.

Revision ID: gov1audit2roe
Revises: job1lease2fence
"""

from __future__ import annotations

import hashlib
import json
from collections import defaultdict
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "gov1audit2roe"
down_revision: str | None = "job1lease2fence"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_GENESIS = "0" * 64


def _backfill_legacy_chains() -> None:
    """Seal pre-upgrade rows into a deterministic legacy chain.

    Historical rows cannot be retroactively authenticated with the deployment
    key because migrations intentionally cannot read application secrets. Their
    key id/algorithm makes that limitation explicit; all rows created after this
    migration carry an HMAC generated by the application.
    """
    bind = op.get_bind()
    rows = bind.execute(
        sa.text(
            "SELECT id, organization_id FROM audit_events ORDER BY organization_id, created_at, id"
        )
    ).mappings()
    state: dict[str, tuple[int, str]] = defaultdict(lambda: (0, _GENESIS))
    for row in rows:
        scope = str(row["organization_id"]) if row["organization_id"] is not None else "global"
        sequence, previous = state[scope]
        signature = hashlib.sha256(f"legacy-audit-event-v1\0{row['id']}".encode()).hexdigest()
        chain_hash = hashlib.sha256(bytes.fromhex(previous) + bytes.fromhex(signature)).hexdigest()
        bind.execute(
            sa.text(
                "UPDATE audit_events SET integrity_version=1, "
                "integrity_algorithm='legacy-sha256-v1', integrity_key_id='legacy', "
                "event_signature=:signature, chain_scope=:scope, "
                "chain_sequence=:sequence, previous_hash=:previous, chain_hash=:chain_hash "
                "WHERE id=:id"
            ),
            {
                "id": row["id"],
                "scope": scope,
                "sequence": sequence + 1,
                "previous": previous,
                "signature": signature,
                "chain_hash": chain_hash,
            },
        )
        state[scope] = (sequence + 1, chain_hash)


def _add_authorization_grants() -> None:
    for name, column_type in (
        ("authorization_owner", sa.String(length=255)),
        ("authorization_source", sa.String(length=64)),
        ("authorization_reference", sa.String(length=255)),
        ("authorization_document_sha256", sa.String(length=64)),
        ("effective_from", sa.DateTime(timezone=True)),
        ("effective_until", sa.DateTime(timezone=True)),
        ("authorized_cidrs_json", sa.JSON()),
        ("authorized_asset_ids_json", sa.JSON()),
        ("authorized_modules_json", sa.JSON()),
        ("policy_digest", sa.String(length=64)),
    ):
        op.add_column("rules_of_engagement", sa.Column(name, column_type, nullable=True))

    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        legacy_update = sa.text(
            "UPDATE rules_of_engagement SET "
            "authorization_owner='legacy unverified grant', "
            "authorization_source='legacy', authorization_reference=:reference, "
            "authorization_document_sha256=:digest, effective_from=created_at, "
            "effective_until=created_at + interval '1 second', authorized_cidrs_json=:empty, "
            "authorized_asset_ids_json=:empty, authorized_modules_json=:empty, "
            "policy_digest=:digest WHERE id=:id"
        )
    else:
        legacy_update = sa.text(
            "UPDATE rules_of_engagement SET "
            "authorization_owner='legacy unverified grant', "
            "authorization_source='legacy', authorization_reference=:reference, "
            "authorization_document_sha256=:digest, effective_from=created_at, "
            "effective_until=datetime(created_at, '+1 second'), authorized_cidrs_json=:empty, "
            "authorized_asset_ids_json=:empty, authorized_modules_json=:empty, "
            "policy_digest=:digest WHERE id=:id"
        )
    rows = bind.execute(sa.text("SELECT id, created_at FROM rules_of_engagement")).mappings()
    for row in rows:
        row_id = str(row["id"])
        digest = hashlib.sha256(f"legacy-roe-v1\0{row_id}".encode()).hexdigest()
        bind.execute(
            legacy_update,
            {
                "id": row["id"],
                "reference": f"legacy:{row_id}",
                "digest": digest,
                "empty": json.dumps([]),
            },
        )
    with op.batch_alter_table("rules_of_engagement") as batch:
        for column in (
            "authorization_owner",
            "authorization_source",
            "authorization_reference",
            "authorization_document_sha256",
            "effective_from",
            "effective_until",
            "authorized_cidrs_json",
            "authorized_asset_ids_json",
            "authorized_modules_json",
            "policy_digest",
        ):
            batch.alter_column(column, nullable=False)
        batch.create_check_constraint("ck_roe_effective_window", "effective_until > effective_from")
        batch.create_check_constraint(
            "ck_roe_document_digest_length", "length(authorization_document_sha256) = 64"
        )
        batch.create_check_constraint("ck_roe_policy_digest_length", "length(policy_digest) = 64")
    op.create_index(
        "ix_rules_of_engagement_policy_digest", "rules_of_engagement", ["policy_digest"]
    )

    op.add_column(
        "pentest_sessions",
        sa.Column("authorization_snapshot_json", sa.JSON(), nullable=True),
    )
    op.execute("UPDATE pentest_sessions SET authorization_snapshot_json = '{}'")
    with op.batch_alter_table("pentest_sessions") as batch:
        batch.alter_column("authorization_snapshot_json", nullable=False)
    op.add_column("pentest_sessions", sa.Column("authorized_network_id", sa.Uuid(), nullable=True))
    op.add_column("pentest_sessions", sa.Column("authorized_probe_id", sa.Uuid(), nullable=True))
    op.add_column("pentest_sessions", sa.Column("authorized_relay_id", sa.Uuid(), nullable=True))
    op.add_column("pentest_sessions", sa.Column("scan_job_attempt_id", sa.Uuid(), nullable=True))
    with op.batch_alter_table("pentest_sessions") as batch:
        batch.create_foreign_key(
            "fk_pentest_sessions_authorized_network_id",
            "networks",
            ["authorized_network_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch.create_foreign_key(
            "fk_pentest_sessions_authorized_probe_id",
            "probes",
            ["authorized_probe_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch.create_foreign_key(
            "fk_pentest_sessions_scan_job_attempt_id",
            "scan_job_attempts",
            ["scan_job_attempt_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch.create_foreign_key(
            "fk_pentest_sessions_authorized_relay_id",
            "relays",
            ["authorized_relay_id"],
            ["id"],
            ondelete="SET NULL",
        )


def upgrade() -> None:
    _add_authorization_grants()
    op.add_column(
        "audit_events",
        sa.Column("integrity_version", sa.Integer(), nullable=True),
    )
    op.add_column(
        "audit_events",
        sa.Column("integrity_algorithm", sa.String(length=32), nullable=True),
    )
    op.add_column(
        "audit_events",
        sa.Column("integrity_key_id", sa.String(length=16), nullable=True),
    )
    op.add_column(
        "audit_events",
        sa.Column("event_signature", sa.String(length=64), nullable=True),
    )
    op.add_column("audit_events", sa.Column("chain_scope", sa.String(length=36), nullable=True))
    op.add_column("audit_events", sa.Column("chain_sequence", sa.BigInteger(), nullable=True))
    op.add_column("audit_events", sa.Column("previous_hash", sa.String(length=64), nullable=True))
    op.add_column("audit_events", sa.Column("chain_hash", sa.String(length=64), nullable=True))

    _backfill_legacy_chains()

    with op.batch_alter_table("audit_events") as batch:
        for column in (
            "integrity_version",
            "integrity_algorithm",
            "integrity_key_id",
            "event_signature",
            "chain_scope",
            "chain_sequence",
            "previous_hash",
            "chain_hash",
        ):
            batch.alter_column(column, nullable=False)
        batch.create_unique_constraint("uq_audit_chain_sequence", ["chain_scope", "chain_sequence"])
    op.create_index("ix_audit_events_chain_scope", "audit_events", ["chain_scope"])
    op.create_index("ix_audit_events_chain_hash", "audit_events", ["chain_hash"])

    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
        op.execute(
            """
            CREATE OR REPLACE FUNCTION vulna_seal_audit_event()
            RETURNS trigger
            LANGUAGE plpgsql
            AS $$
            DECLARE
                prior_sequence bigint;
                prior_hash text;
            BEGIN
                NEW.chain_scope := COALESCE(NEW.organization_id::text, 'global');
                PERFORM pg_advisory_xact_lock(hashtextextended(NEW.chain_scope, 0));
                SELECT chain_sequence, chain_hash
                  INTO prior_sequence, prior_hash
                  FROM audit_events
                 WHERE chain_scope = NEW.chain_scope
                 ORDER BY chain_sequence DESC
                 LIMIT 1;
                NEW.chain_sequence := COALESCE(prior_sequence, 0) + 1;
                NEW.previous_hash := COALESCE(prior_hash, repeat('0', 64));
                NEW.chain_hash := encode(
                    digest(
                        decode(NEW.previous_hash, 'hex') ||
                        decode(NEW.event_signature, 'hex'),
                        'sha256'
                    ),
                    'hex'
                );
                RETURN NEW;
            END;
            $$
            """
        )
        op.execute(
            """
            CREATE TRIGGER trg_audit_events_seal
            BEFORE INSERT ON audit_events
            FOR EACH ROW EXECUTE FUNCTION vulna_seal_audit_event()
            """
        )
        op.execute(
            """
            CREATE OR REPLACE FUNCTION vulna_reject_audit_mutation()
            RETURNS trigger
            LANGUAGE plpgsql
            AS $$
            BEGIN
                RAISE EXCEPTION '% is append-only', TG_TABLE_NAME;
            END;
            $$
            """
        )
        op.execute(
            """
            CREATE TRIGGER trg_rules_of_engagement_immutable
            BEFORE UPDATE OR DELETE ON rules_of_engagement
            FOR EACH ROW EXECUTE FUNCTION vulna_reject_audit_mutation()
            """
        )
        op.execute(
            """
            CREATE TRIGGER trg_audit_events_immutable
            BEFORE UPDATE OR DELETE ON audit_events
            FOR EACH ROW EXECUTE FUNCTION vulna_reject_audit_mutation()
            """
        )


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            "DROP TRIGGER IF EXISTS trg_rules_of_engagement_immutable ON rules_of_engagement"
        )
        op.execute("DROP TRIGGER IF EXISTS trg_audit_events_immutable ON audit_events")
        op.execute("DROP FUNCTION IF EXISTS vulna_reject_audit_mutation()")
        op.execute("DROP TRIGGER IF EXISTS trg_audit_events_seal ON audit_events")
        op.execute("DROP FUNCTION IF EXISTS vulna_seal_audit_event()")
    with op.batch_alter_table("pentest_sessions") as batch:
        batch.drop_constraint("fk_pentest_sessions_authorized_relay_id", type_="foreignkey")
        batch.drop_constraint("fk_pentest_sessions_scan_job_attempt_id", type_="foreignkey")
        batch.drop_constraint("fk_pentest_sessions_authorized_probe_id", type_="foreignkey")
        batch.drop_constraint("fk_pentest_sessions_authorized_network_id", type_="foreignkey")
    op.drop_column("pentest_sessions", "scan_job_attempt_id")
    op.drop_column("pentest_sessions", "authorized_relay_id")
    op.drop_column("pentest_sessions", "authorized_probe_id")
    op.drop_column("pentest_sessions", "authorized_network_id")
    op.drop_column("pentest_sessions", "authorization_snapshot_json")
    op.drop_index("ix_rules_of_engagement_policy_digest", table_name="rules_of_engagement")
    with op.batch_alter_table("rules_of_engagement") as batch:
        batch.drop_constraint("ck_roe_policy_digest_length", type_="check")
        batch.drop_constraint("ck_roe_document_digest_length", type_="check")
        batch.drop_constraint("ck_roe_effective_window", type_="check")
    for column in (
        "policy_digest",
        "authorized_modules_json",
        "authorized_asset_ids_json",
        "authorized_cidrs_json",
        "effective_until",
        "effective_from",
        "authorization_document_sha256",
        "authorization_reference",
        "authorization_source",
        "authorization_owner",
    ):
        op.drop_column("rules_of_engagement", column)
    with op.batch_alter_table("audit_events") as batch:
        batch.drop_constraint("uq_audit_chain_sequence", type_="unique")
    op.drop_index("ix_audit_events_chain_hash", table_name="audit_events")
    op.drop_index("ix_audit_events_chain_scope", table_name="audit_events")
    for column in (
        "chain_hash",
        "previous_hash",
        "chain_sequence",
        "chain_scope",
        "event_signature",
        "integrity_key_id",
        "integrity_algorithm",
        "integrity_version",
    ):
        op.drop_column("audit_events", column)
